export const statesAndTerritories = [ 
"Alabama (AL)", 
"Alaska (AK)",
"Arizona (AZ)",
"Arkansas (AR)",
"California (CA)",
"Colorado (CO)",
"Connecticut (CT)",
"Delaware (DE)",
"District of Columbia (DC)",
"Florida (FL)",
"Georgia (GA)",
"Hawaii (HI)",
"Idaho (ID)",
"Illinois (IL)",
"Indiana (IN)",
"Iowa (IA)",
"Kansas (KS)",
"Kentucky (KY)",
"Louisiana (LA)",
"Maine (ME)",
"Maryland (MD)",
"Massachusetts (MA)",
"Michigan (MI)",
"Minnesota (MN)",
"Mississippi (MS)",
"Missouri (MO)",
"Montana (MT)",
"Nebraska (NE)",
"Nevada (NV)",
"New Hampshire (NH)",
"New Jersey (NJ)",
"New Mexico (NM)",
"New York (NY)",
"North Carolina (NC)",
"North Dakota (ND)",
"Ohio (OH)",
"Oklahoma (OK)",
"Oregon (OR)",
"Pennsylvania (PA)",
"Rhode Island (RI)",
"South Carolina",
"South Dakota",
"Tennessee",
"Texas",
"Utah",
"Vermont",
"Virginia",
"Washington",
"West Virginia",
"Wisconsin",
"Wyoming",
]


export const emailList = [
"bgenike0@guardian.co.uk",
"omacenelly1@ucoz.ru",
"bgoodhay2@apple.com",
"mvint3@biblegateway.com",
"gqueyeiro4@microsoft.com",
"imaxweell5@gov.uk",
"dcastiblanco6@netvibes.com",
"jwalker7@squarespace.com",
"smundle8@51.la",
"laddess9@mediafire.com",
"lgroucocka@oaic.gov.au",
"cdudillb@goodreads.com",
"gquiltyc@accuweather.com",
"achiezed@ameblo.jp",
"gsymingtone@slideshare.net",
"mmennellf@reverbnation.com",
"cberrymang@abc.net.au",
"omelluishh@state.gov",
"adarkoi@vinaora.com",
"cparres15@sourceforge.net",
"dfriar16@psu.edu",
"cbenedikt17@samsung.com",
"vyorath18@bluehost.com",
"adarth19@shutterfly.com",
"lhamer1a@ycombinator.com",
"pmceachern1b@yolasite.com",
"hlevy1c@php.net",
"lredihough1o@histats.com",
"lgrieswood1p@simplemachines.org",
"mrevill1q@tiny.cc",
"eleyborne1r@istockphoto.com",
"bmccoy1s@google.pl",
"gsambedge1t@mapquest.com",
]

export const usernameList = [
"chitter0",
"afears1",
"mblankhorn2",
"lcoaker3",
"sknight4",
"dcheeld5",
"tcawthra6",
"pkinzel7",
"abreem8",
"jkruschev9",
"rpitkinsa",
"amuddb",
"edoeyc",
"mrothertd",
"wdettmare",
"lconnopf",
"gsmitheramg",
"imarquissh",
"sheathcotti",
"chousdenj",
"lmolyneauxk",
"cgabbattl",
"ckenwinm",
"aloachheadn",
"chuberyo",
"ckoppesp",
"cstainfieldq",
"egoeringr",
"baddenbrookes",
"pzecchinit",
"kwaddilow0",
"gvasyunin1",
"amount2",
"awathen3",
"hmenary4",
"nblankman5",
"vmatterson6",
"uhorsburgh7",
"mblockley8",
"ioret9",
"bandrettia",
"jrymellb",
"dburtc",
"dstandbridged",
"pbrauntone",
]